ski<-read.table(file = file.choose(),header = T,sep = "\t")
View(ski)
str(ski)
summary(ski$age)
sd(ski$age)
ski[which.max(ski$age),]
res<-hist(ski$age,breaks = seq(11,80,5),plot = FALSE,right = TRUE)
paste(res$breaks[which.max(res$counts)],res$breaks[which.max(res$counts)+1])
res<-hist(ski$age,breaks = seq(11,80,5),right = TRUE)
boxplot(ski$age)
levels(as.factor(ski$Q5_lieu))
levels(as.factor(ski$Q6_niveau))
table(as.factor(ski$Q5_lieu))
table(as.factor(ski$Q6_niveau))
table(as.factor(ski$Q5_lieu))/nrow(ski)
table(as.factor(ski$Q6_niveau))/nrow(ski)
names(which.max(table(as.factor(ski$Q5_lieu))))
names(which.max(table(as.factor(ski$Q6_niveau))))
barplot(table(as.factor(ski$Q5_lieu)))
pie(table(as.factor(ski$Q6_niveau)))