data<-read.table(file = file.choose(),header = T,sep = "")
View(data)
names(data)
str(data)
summary(data$POSTE)
str(data$POSTE)
table(data$POSTE)
prop.table(data$POSTE)
table(data$POSTE)/nrow(data)
pie(table(data$POSTE)/nrow(data))
barplot(table(data$POSTE)/nrow(data))
barplot(table(data$POSTE))
summary(data$TAD)
hist(data$TAD)
length(data[data$TAD>175&data$TAD<=180,])
