data <-read.table(file=file.choose(),header = TRUE,sep = ";",)
View(data)
summary(data)
str(data)
sum(is.na(data)/prod(dim(data)))
dat.moy<-impute(data$NO2,fun = mean)
class(dat.moy)
summary(dat.moy)
dat.moy<=as.vector(dat.moy)
dat.moy1<-impute(data$NO2,fun = random)
class(dat.moy1)
summary(dat.moy1)

datt=KNN()